### ISSUE TITLE
FlagValueChanged not firing on first event if AutoEnvAttributes is enabled

### ISSUE THREAD

**Issue by jbrookssmokeball** [launchdarkly/dotnet-client-sdk#70] opened 2024-01-08 05:06 UTC
**Description**
The FlagValueChanged event does not fire on the first event after initializing if `AutoEnvAttributes` is enabled.

**To reproduce**
Use the following code to initialize `LdClient` with `AutoEnvAttributes` enabled: (update `YOUR_USER_ID` with any LD user's ID and `YOUR_KEY` with your SDK key).
```
var builder = Context
    .Builder(ContextKind.Default, "YOUR_USER_ID");

var context = builder.Build();

var configuration = Configuration
    .Builder("YOUR_KEY", ConfigurationBuilder.AutoEnvAttributes.Enabled)
    .Build();

var ldClient = LdClient.Init(
    configuration,
    context,
    TimeSpan.FromSeconds(30));

ldClient.FlagTracker.FlagValueChanged += NotifyFlagValueChanged;
```

The `NotifyFlagValueChanged` function looks like:
```
private void NotifyFlagValueChanged(object sender, FlagValueChangeEvent e)
{
    Console.WriteLine($"Received change: {e.Key} from {e.OldValue} to {e.NewValue}");
}
```

Run the code and make a change to a flag on LaunchDarkly that will change the evaluated value for the user.

**Expected behavior**
The flag change event is received by the client side code.

**Actual behavior**
The first flag change event is not received by the client side code.
Subsequent flag change events are received by the client side code.

**SDK version**
LaunchDarkly.ClientSdk 4.0.0

**Language version, developer tools**
C#

**OS/platform**
Windows 11, .NET 6

**Additional context**
If `AutoEnvAttributes` is disabled, then this works as expected.
Unable to reproduce on LaunchDarkly.ClientSdk 3.1.0.

**Comment by tanderson-ld** [comment] 2024-01-08 16:04
Thank you for bringing this to our attention.  I will investigate and respond once completed.

**Comment by tanderson-ld** [comment] 2024-06-03 15:00
Logged as SC-246089

**Comment by tanderson-ld** [comment] 2024-06-03 20:49
@jbrookssmokeball , I have been able to reproduce the issue and am investigating the root cause now.

**Comment by tanderson-ld** [comment] 2024-06-04 19:59
We have opened a PR for the fix and should have that released in the next day or two.  [PR is here.](https://github.com/launchdarkly/dotnet-client-sdk/pull/97)

**Comment by tanderson-ld** [comment] 2024-06-05 19:54
Version 5.2.1 has been released with the fix.  Thank you for your help!

**Closed by tanderson-ld** 2024-06-05 19:54 UTC
